"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CheckCircle2, ChevronDown, ChevronUp, UploadCloud } from "lucide-react";
import { allocationByAsset, auditRows, comparisonOutcomes, contributionSeries, formatMoney, healthItems, holdings, instrumentOptions, marketSeries, marketUnavailable, monthlyReturns, overviewMetrics, portfolioMetrics, portfolioSeries, recentSignals, researchDrawdown, researchEquityCurve, researchRuns, riskStatus, shadowComparisonSummary, signals, warnings } from "@/data/mockData";
import { EvidenceRow, Holding, PageKey, SignalRow } from "@/types";
import { AppShell } from "@/components/AppShell";
import { ChartCard } from "@/components/ChartCard";
import { DataTable, TableColumn } from "@/components/DataTable";
import { EvidenceHash } from "@/components/EvidenceHash";
import { HealthIndicator } from "@/components/HealthIndicator";
import { MarketChart } from "@/components/MarketChart";
import { MetricCard } from "@/components/MetricCard";
import { StatusBadge } from "@/components/StatusBadge";
import { OverviewIntegration } from "@/components/OverviewIntegration";

const grid = <CartesianGrid stroke="#243640" vertical={false} />;
const axis = { stroke: "#b1c0c8", fontSize: 14, tickLine: false, axisLine: false };
const tooltip = { contentStyle: { background: "#111c24", border: "1px solid #405761", borderRadius: "8px", fontSize: 14 }, labelStyle: { color: "#e2e8f0" } };
const recentShadowRuns = [
  { runId: "shadow_20260811_a", timestamp: "11 Aug 2026, 15:44", result: "Complete", agreement: "12 agree · 3 differ" },
  { runId: "shadow_20260810_b", timestamp: "10 Aug 2026, 15:44", result: "Complete", agreement: "14 agree · 2 unavailable" },
  { runId: "shadow_20260809_c", timestamp: "09 Aug 2026, 15:44", result: "Reviewed", agreement: "13 agree · 1 mismatch" },
];
const holdingColumns: TableColumn<Holding>[] = [
  { key: "instrument", label: "Instrument", sortable: true, render: r => <div><b>{r.instrument}</b><div className="text-sm text-slate-400">{r.name}</div></div> },
  { key: "assetClass", label: "Asset class", sortable: true }, { key: "weight", label: "Weight", sortable: true, className: "text-right tabular-nums", render: r => `${r.weight.toFixed(1)}%`, sortValue: r => r.weight },
  { key: "marketValue", label: "Value", sortable: true, className: "text-right tabular-nums", render: r => formatMoney(r.marketValue), sortValue: r => r.marketValue },
  { key: "dayPnl", label: "Today", sortable: true, className: "text-right tabular-nums", render: r => <span className={r.dayPnl >= 0 ? "text-mint" : "text-danger"}>{formatMoney(r.dayPnl)}</span>, sortValue: r => r.dayPnl },
  { key: "signal", label: "Signal", sortable: true, render: r => <StatusBadge label={r.signal} tone={r.signal === "BUY" ? "positive" : r.signal === "HOLD" ? "neutral" : "warning"} /> },
];
const signalColumns: TableColumn<SignalRow>[] = [
  { key: "instrument", label: "Instrument", sortable: true }, { key: "assetClass", label: "Asset class", sortable: true },
  { key: "signal", label: "Signal", sortable: true, render: r => <StatusBadge label={r.signal} tone={r.signal === "BUY" ? "positive" : r.signal === "HOLD" ? "neutral" : "warning"} /> },
  { key: "target", label: "Target", className: "text-right tabular-nums" }, { key: "comparison", label: "Comparison", sortable: true, render: r => <StatusBadge label={r.comparison} tone={r.comparison === "Agree" ? "positive" : r.comparison === "Differ" ? "warning" : "negative"} /> },
];
const auditColumns: TableColumn<EvidenceRow>[] = [
  { key: "timestamp", label: "Timestamp", sortable: true }, { key: "artifact", label: "Artifact", sortable: true }, { key: "classification", label: "Classification", sortable: true }, { key: "verification", label: "Status", sortable: true }, { key: "hash", label: "SHA-256", render: r => <EvidenceHash value={r.hash} /> },
];
const shadowColumns: TableColumn<(typeof recentShadowRuns)[number]>[] = [
  { key: "runId", label: "Run ID" }, { key: "timestamp", label: "Timestamp" }, { key: "result", label: "Result", render: r => <StatusBadge label={r.result} tone="positive" /> }, { key: "agreement", label: "Agreement summary" },
];

function Details({ title, children, defaultOpen = false }: { title: string; children: React.ReactNode; defaultOpen?: boolean }) { const [open, setOpen] = useState(defaultOpen); return <div className="border-t border-slate-700/70 pt-4"><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between text-base font-medium text-slate-200">{title}{open ? <ChevronUp size={18}/> : <ChevronDown size={18}/>}</button>{open ? <div className="pt-4">{children}</div> : null}</div>; }
function Drawer({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50"><div className="modal-backdrop absolute inset-0" onClick={onClose}/><section className="absolute right-0 top-0 h-full w-full max-w-md overflow-y-auto border-l border-slate-700 bg-[#111c24] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">{title}</h2><button onClick={onClose} className="rounded-lg border border-slate-600 px-3 py-2 text-sm">Close</button></div><div className="mt-6">{children}</div></section></div>; }

export function DashboardClient({ page }: { page: PageKey }) {
  const [selectedHolding, setSelectedHolding] = useState<Holding | null>(null); const [selectedEvidence, setSelectedEvidence] = useState<EvidenceRow | null>(null);
  const [asset, setAsset] = useState("All"); const [signal, setSignal] = useState("All"); const [outcome, setOutcome] = useState("All"); const [run, setRun] = useState(researchRuns[0].value); const [market, setMarket] = useState("IUSA.L"); const [exportOn, setExportOn] = useState(false); const [attached, setAttached] = useState(false);
  const filteredSignals = useMemo(() => signals.filter(s => (asset === "All" || s.assetClass === asset) && (signal === "All" || s.signal === signal) && (outcome === "All" || s.comparison === outcome)), [asset, signal, outcome]);

  const overview = <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{overviewMetrics.filter(m => ["Portfolio Value", "Today", "Total Return", "Cash"].includes(m.label)).map(m => <MetricCard key={m.label} item={m}/>)}</div><div className="grid gap-5 xl:grid-cols-[minmax(0,1.8fr)_minmax(300px,.8fr)]"><ChartCard title="Portfolio performance" subtitle="Portfolio versus SPY, converted to GBP"><div className="h-[390px]"><ResponsiveContainer><LineChart data={portfolioSeries}>{grid}<XAxis dataKey="date" {...axis}/><YAxis {...axis}/><Tooltip {...tooltip}/><Legend wrapperStyle={{ fontSize: 14 }}/><Line type="monotone" dataKey="portfolio" name="Portfolio" stroke="#72c59a" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="benchmark" name="SPY (GBP)" stroke="#5fb8b1" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></ChartCard><div className="space-y-5"><ChartCard title="Allocation"><div className="h-[210px]"><ResponsiveContainer><PieChart><Pie data={allocationByAsset} dataKey="value" nameKey="name" innerRadius={55} outerRadius={82}>{allocationByAsset.map(x => <Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip {...tooltip}/></PieChart></ResponsiveContainer></div><div className="space-y-2.5 text-[15px]">{allocationByAsset.slice(0, 4).map(x => <div key={x.name} className="flex justify-between text-slate-300"><span>{x.name}</span><span className="tabular-nums">{x.value}%</span></div>)}</div></ChartCard><ChartCard title="Risk summary"><div className="space-y-3">{riskStatus.slice(0, 4).map(x => <div key={x.label} className="flex items-center justify-between text-[15px]"><span className="text-slate-300">{x.label}</span><span className="text-slate-100">{x.value}</span></div>)}</div></ChartCard></div></div><div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><ChartCard title="Recent signals"><div className="divide-y divide-slate-700/60">{recentSignals.map(x => <div key={x.instrument} className="flex items-center justify-between py-3.5"><div><b className="text-base">{x.instrument}</b><p className="text-[15px] text-slate-300">{x.note}</p></div><StatusBadge label={x.action} tone={x.action === "BUY" ? "positive" : "warning"}/></div>)}</div></ChartCard><ChartCard title="Current holdings" subtitle="Select a row for position detail"><DataTable data={holdings} columns={holdingColumns.slice(0, 4)} onRowClick={setSelectedHolding}/></ChartCard></div></div>;
  const integratedOverview = <OverviewIntegration fallback={overview} />;
  const portfolio = <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{portfolioMetrics.filter(m => ["Total Equity", "Cash", "Unrealized P&L", "Exposure"].includes(m.label)).map(m => <MetricCard key={m.label} item={m}/>)}</div><div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Allocation"><div className="grid items-center gap-2 sm:grid-cols-[1fr_190px]"><div className="h-[330px]"><ResponsiveContainer><PieChart><Pie data={allocationByAsset} dataKey="value" nameKey="name" innerRadius={75} outerRadius={112}>{allocationByAsset.map(x => <Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip {...tooltip}/></PieChart></ResponsiveContainer></div><div className="space-y-3 text-[15px]">{allocationByAsset.map(x => <div key={x.name} className="flex items-center justify-between gap-2 text-slate-300"><span className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: x.color }}/>{x.name}</span><b className="tabular-nums text-slate-100">{x.value}%</b></div>)}</div></div></ChartCard><ChartCard title="Contribution to return"><div className="h-[330px]"><ResponsiveContainer><BarChart data={contributionSeries}>{grid}<XAxis dataKey="date" {...axis}/><YAxis {...axis}/><Tooltip {...tooltip}/><Bar dataKey="contribution" fill="#5fb8b1" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></ChartCard></div><ChartCard title="Holdings" subtitle="Select a holding to see the full position detail"><DataTable data={holdings} columns={holdingColumns} onRowClick={setSelectedHolding}/></ChartCard></div>;
  const markets = <div className="space-y-6"><div className="flex flex-wrap items-center gap-3"><label className="text-base text-slate-300">Instrument <select value={market} onChange={e => setMarket(e.target.value)} className="ml-2 rounded-lg border border-slate-600 bg-[#111c24] px-3 py-2 text-base text-slate-100">{instrumentOptions.map(o => <option key={o.value}>{o.label}</option>)}</select></label>{market === "AAPL" ? <StatusBadge label="Quote delayed" tone="warning"/> : null}</div><div className="grid gap-5 xl:grid-cols-[minmax(0,1.7fr)_minmax(280px,.7fr)]"><ChartCard title={`${market} price`} subtitle="Daily OHLC · local mock preview"><MarketChart data={marketSeries}/><p className="mt-3 text-[15px] text-slate-300">Moving averages: teal (short) and amber (long).</p></ChartCard><div className="space-y-5"><ChartCard title="Current quote"><div className="text-4xl font-semibold">GBP 175.16</div><div className="mt-1.5 text-base text-mint">+0.26% today</div><dl className="mt-5 grid grid-cols-2 gap-3 text-base"><dt className="text-slate-400">Open</dt><dd>174.70</dd><dt className="text-slate-400">High</dt><dd>175.80</dd><dt className="text-slate-400">Low</dt><dd>173.90</dd><dt className="text-slate-400">Close</dt><dd>175.16</dd></dl></ChartCard><ChartCard title="Market data"><p className="text-[15px] text-slate-200">Completed daily bar · Fresh local preview</p><Details title="Details"><p className="text-[15px] text-slate-300">Listing currency: GBP · Price unit: per share · Source: local mock data</p></Details></ChartCard></div></div>{market === marketUnavailable.instrument ? <p className="rounded-lg border border-amber/25 bg-amber/10 px-4 py-3 text-[15px] text-amber">{marketUnavailable.reason}</p> : null}</div>;
  const signalView = <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><MetricCard item={{ label: "Buy", value: "2", tone: "positive" }}/><MetricCard item={{ label: "Hold", value: "2", tone: "neutral" }}/><MetricCard item={{ label: "Unavailable", value: "1", tone: "warning" }}/></div><ChartCard title="Strategy signals" subtitle="Technical signals only"><div className="mb-5 grid gap-3 sm:grid-cols-3"><label className="text-sm text-slate-300">Asset class<select value={asset} onChange={e => setAsset(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-600 bg-[#111c24] px-3 py-2.5 text-base text-slate-100"><option>All</option>{[...new Set(signals.map(s => s.assetClass))].map(x => <option key={x}>{x}</option>)}</select></label><label className="text-sm text-slate-300">Signal<select value={signal} onChange={e => setSignal(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-600 bg-[#111c24] px-3 py-2.5 text-base text-slate-100"><option>All</option><option>BUY</option><option>HOLD</option><option>UNAVAILABLE</option></select></label><label className="text-sm text-slate-300">Comparison<select value={outcome} onChange={e => setOutcome(e.target.value)} className="mt-1 block w-full rounded-lg border border-slate-600 bg-[#111c24] px-3 py-2.5 text-base text-slate-100"><option>All</option>{comparisonOutcomes.map(x => <option key={x}>{x}</option>)}</select></label></div><DataTable data={filteredSignals} columns={signalColumns}/><Details title="Signal fields and evidence"><div className="mt-2 space-y-2 text-[15px] text-slate-300">{filteredSignals.map(s => <div key={s.instrument}>{s.instrument}: {s.reason} · Evidence {s.evidence} · Decision {s.decision}</div>)}</div></Details></ChartCard></div>;
  const research = <div className="space-y-6"><div className="flex flex-wrap items-center gap-3"><label className="text-base text-slate-300">Research run <select value={run} onChange={e => setRun(e.target.value)} className="ml-2 rounded-lg border border-slate-600 bg-[#111c24] px-3 py-2 text-base text-slate-100">{researchRuns.map(r => <option key={r.value} value={r.value}>{r.label}</option>)}</select></label><StatusBadge label="Exploratory · unverified" tone="warning"/></div><div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><ChartCard title="Equity curve" subtitle="Research run versus SPY (GBP)"><div className="h-[410px]"><ResponsiveContainer><LineChart data={researchEquityCurve}>{grid}<XAxis dataKey="date" {...axis}/><YAxis {...axis}/><Tooltip {...tooltip}/><Legend wrapperStyle={{ fontSize: 14 }}/><Line type="monotone" dataKey="portfolio" name="Research run" stroke="#72c59a" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="benchmark" name="SPY (GBP)" stroke="#5fb8b1" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></ChartCard><ChartCard title="Drawdown"><div className="h-[410px]"><ResponsiveContainer><AreaChart data={researchDrawdown}>{grid}<XAxis dataKey="date" {...axis}/><YAxis {...axis}/><Tooltip {...tooltip}/><Area dataKey="drawdown" stroke="#d77875" fill="#d7787530"/></AreaChart></ResponsiveContainer></div></ChartCard></div><ChartCard title="Monthly returns"><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{monthlyReturns.map(([m, v]) => <div key={m} className={`rounded-lg px-3 py-3.5 text-center text-[15px] ${v >= 0 ? "bg-mint/10 text-mint" : "bg-danger/10 text-danger"}`}><div className="text-slate-300">{m}</div><b>{v}%</b></div>)}</div><Details title="Run information"><p className="text-[15px] text-slate-300">{run} · turnover 18.4% · fees 12 bps · results not approved for capital. No live execution, partial fills, market impact, or point-in-time fundamentals.</p></Details></ChartCard></div>;
  const shadow = <div className="compact-page-wide space-y-6"><div className="grid w-full gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(360px,.9fr)]"><ChartCard title="Comparison outcome" subtitle="Validated and legacy outputs"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{shadowComparisonSummary.map(x => <div key={x.label} className="rounded-lg bg-white/[.035] p-4"><div className="text-[15px] text-slate-300">{x.label}</div><div className="mt-1 text-3xl font-semibold">{x.value}</div></div>)}</div><p className="mt-4 text-[15px] text-slate-300">Mock completed comparison. UI preview only.</p></ChartCard><ChartCard title="Manual input"><button onClick={() => setAttached(true)} className="flex w-full items-center justify-center gap-3 rounded-lg border border-dashed border-slate-600 px-5 py-8 text-base text-slate-200 hover:border-[#5fb8b1]"><UploadCloud size={20}/> {attached ? "mock_input.json attached" : "Add a mock input file"}</button><Details title="Advanced export settings"><label className="mt-3 flex items-center justify-between text-base">Enable export <input type="checkbox" checked={exportOn} onChange={e => setExportOn(e.target.checked)} className="accent-cyan"/></label><input disabled={!exportOn} value={exportOn ? "C:\\preview\\shadow-output" : ""} readOnly className="mt-3 w-full rounded-lg border border-slate-600 bg-transparent px-3 py-2.5 text-base disabled:opacity-50"/></Details></ChartCard></div><ChartCard title="Recent runs"><DataTable data={recentShadowRuns} columns={shadowColumns}/></ChartCard></div>;
  const risk = <div className="compact-page-wide space-y-6"><div className="grid w-full gap-4 sm:grid-cols-2 xl:grid-cols-4">{healthItems.slice(0, 4).map(x => <HealthIndicator key={x.label} label={x.label} value={x.value} tone={x.tone}/>)}</div><div className="grid w-full gap-5 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,.9fr)]"><ChartCard title="Important controls"><div className="grid gap-3 sm:grid-cols-2">{riskStatus.slice(0, 4).map(x => <div key={x.label} className="rounded-lg bg-white/[.035] px-4 py-3.5"><div className="text-[15px] text-slate-300">{x.label}</div><div className="mt-1 text-lg font-medium">{x.value}</div></div>)}</div><Details title="Routine checks"><div className="grid gap-2 sm:grid-cols-2">{healthItems.slice(4).map(x => <div key={x.label} className="text-[15px] text-slate-300">{x.label}: <span className="text-slate-100">{x.value}</span></div>)}</div></Details></ChartCard><ChartCard title="Active warnings"><div className="space-y-3">{warnings.map(w => <div key={w} className="rounded-lg border-l-2 border-amber bg-amber/5 px-4 py-3.5 text-[15px] text-slate-200">{w}</div>)}</div></ChartCard></div></div>;
  const audit = <div className="compact-page-wide space-y-6"><div className="grid w-full gap-4 sm:grid-cols-3"><MetricCard item={{ label: "Verified artifacts", value: "3", tone: "positive" }}/><MetricCard item={{ label: "Unverified", value: "1", tone: "warning" }}/><MetricCard item={{ label: "Partial", value: "1", tone: "negative" }}/></div><ChartCard title="Evidence" subtitle="Select an item to view verification, hashes, versions and provenance"><DataTable data={auditRows} columns={auditColumns} onRowClick={setSelectedEvidence}/></ChartCard></div>;
  const view: Record<PageKey, React.ReactNode> = { Overview: integratedOverview, Portfolio: portfolio, Markets: markets, Signals: signalView, Research: research, "Shadow Runs": shadow, "Risk & Health": risk, Audit: audit };
  return <AppShell title={page}>{view[page]}{selectedHolding ? <Drawer title={selectedHolding.instrument} onClose={() => setSelectedHolding(null)}><div className="space-y-3">{[["Holding", selectedHolding.name], ["Quantity", selectedHolding.quantity], ["Average cost", selectedHolding.avgCost], ["Current value", formatMoney(selectedHolding.marketValue)], ["Total P&L", formatMoney(selectedHolding.totalPnl)], ["Weight", `${selectedHolding.weight}%`], ["Stop", selectedHolding.stop], ["Target", selectedHolding.target]].map(([k, v]) => <div key={k} className="flex justify-between border-b border-slate-700/70 py-2.5 text-base"><span className="text-slate-300">{k}</span><span>{v}</span></div>)}</div><Details title="Data details"><p className="text-[15px] text-slate-300">{selectedHolding.listingCurrency} · {selectedHolding.priceUnit} · {selectedHolding.evidence}</p></Details></Drawer> : null}{selectedEvidence ? <Drawer title={selectedEvidence.artifact} onClose={() => setSelectedEvidence(null)}><div className="space-y-4 text-base"><div><span className="text-slate-300">Run ID</span><p>{selectedEvidence.runId}</p></div><div><span className="text-slate-300">Verification</span><p>{selectedEvidence.verification}</p></div><EvidenceHash value={selectedEvidence.hash}/><Details title="Manifest and provenance" defaultOpen><p className="text-[15px] text-slate-300">Dataset {selectedEvidence.dataset} · Code {selectedEvidence.code} · {selectedEvidence.mutability}</p><ul className="mt-3 space-y-2">{selectedEvidence.manifest.map(x => <li key={x} className="flex gap-2"><CheckCircle2 size={15} className="text-mint"/>{x}</li>)}</ul></Details></div></Drawer> : null}</AppShell>;
}
